paths:
  uploads: uploads
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  proker:
    path: _proker
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  anggota:
    path: _anggota
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  logo:
    mobile: images/logo/logo-mobile.png
    mobile_height: 32px
    mobile_width: 32px
    desktop: images/logo/logo.png
    desktop_height: 32px
    desktop_width: 32px
  home:
    limit_services: 6
  sass:
    style: compressed
  env:
    RUBY_CONFIGURE_OPTS: '--disable-install-doc --with-openssl-dir=/openssl'
    MENTOS_TIMEOUT: '20'
    NVM_INC: /usr/local/.nvm/versions/node/v18.13.0/include/node
    HOSTNAME: 69bc13169745
    LANGUAGE: en_US.UTF-8
    RBENV_HOOK_PATH: >-
      /usr/local/.rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks
    HUGO_VERSION: 0.109.0
    DVM_DIR: /usr/local/.dvm
    RBENV_SHELL: bash
    JEKYLL_ENV: production
    PWD: /usr/local/__site/src
    TZ: UTC
    HOME: /usr/local
    LANG: en_US.UTF-8
    NVM_DIR: /usr/local/.nvm
    RBENV_DIR: /usr/local/__site/src
    DENO_VERSION: 1.30.1
    SHLVL: '2'
    NVM_CD_FLAGS: ''
    BASH_ENV: /usr/local/.bash_profile
    LC_MESSAGES: en_US.UTF-8
    RBENV_VERSION: 2.7.3
    LC_CTYPE: en_US.UTF-8
    NODE_PATH: /usr/local/.nvm/versions/node/v18.13.0/lib/node_modules
    LC_ALL: en_US.UTF-8
    PATH: >-
      /usr/local/__bundle/ruby/2.7.0/bin:/usr/local/.rbenv/versions/2.7.3/bin:/usr/local/.rbenv/libexec:/usr/local/.rbenv/plugins/ruby-build/bin:/usr/local/.rbenv/shims:/usr/local/.dvm/bin:/usr/local/.local/bin:/usr/local/sass/bin:/usr/local/hugo/bin:/usr/local/.nvm/versions/node/v18.13.0/bin:/usr/local/go/versions/go1.19.5.linux.amd64/bin:/usr/local/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    NVM_BIN: /usr/local/.nvm/versions/node/v18.13.0/bin
    NODE_VERSION: 18.13.0
    RUBYLIB: >-
      /usr/local/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib:/usr/local/.rbenv/rbenv.d/exec/gem-rehash
    RBENV_ROOT: /usr/local/.rbenv
    RUBYOPT: >-
      -r/usr/local/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/setup
      -W0 -E utf-8
    OLDPWD: /usr/local/__site/src
    BUNDLER_ORIG_BUNDLE_BIN_PATH: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
    BUNDLER_ORIG_BUNDLE_GEMFILE: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
    BUNDLER_ORIG_BUNDLER_VERSION: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
    BUNDLER_ORIG_BUNDLER_SETUP: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
    BUNDLER_ORIG_GEM_HOME: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
    BUNDLER_ORIG_GEM_PATH: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
    BUNDLER_ORIG_MANPATH: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
    BUNDLER_ORIG_PATH: >-
      /usr/local/.rbenv/versions/2.7.3/bin:/usr/local/.rbenv/libexec:/usr/local/.rbenv/plugins/ruby-build/bin:/usr/local/.rbenv/shims:/usr/local/.dvm/bin:/usr/local/.local/bin:/usr/local/sass/bin:/usr/local/hugo/bin:/usr/local/.nvm/versions/node/v18.13.0/bin:/usr/local/go/versions/go1.19.5.linux.amd64/bin:/usr/local/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    BUNDLER_ORIG_RB_USER_INSTALL: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
    BUNDLER_ORIG_RUBYLIB: '/usr/local/.rbenv/rbenv.d/exec/gem-rehash:'
    BUNDLER_ORIG_RUBYOPT: '-W0 -E utf-8'
    BUNDLE_BIN_PATH: >-
      /usr/local/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/exe/bundle
    BUNDLE_GEMFILE: /usr/local/__site/src/Gemfile
    BUNDLER_VERSION: 2.4.13
    BUNDLER_SETUP: >-
      /usr/local/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/setup
    GEM_PATH: ''
    GEM_HOME: /usr/local/__bundle/ruby/2.7.0
    MANPATH: '/usr/local/__bundle/ruby/2.7.0/gems/kramdown-2.4.0/man:'
    JEKYLL_NO_BUNDLER_REQUIRE: 'true'
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
